apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: init-kafka
  name: init-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: init-kafka
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: init-kafka
    spec:
      containers:
        - args:
            - |2

              # blocks until kafka is reachable
              kafka-topics --bootstrap-server kafka-1:9092 --list

              echo -e 'Creating kafka topics'
              kafka-topics --bootstrap-server kafka-1:9092 --create --if-not-exists --topic my-topic-1 --replication-factor 1 --partitions 1

              echo -e 'Successfully created the following topics:'
              kafka-topics --bootstrap-server kafka-1:9092 --list
          command:
            - /bin/sh
            - -c
          image: confluentinc/cp-kafka:latest
          name: init-kafka
          resources: {}
      restartPolicy: Always
status: {}
