apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: microservice-2
  name: microservice-2
spec:
  ports:
    - name: "28081"
      port: 28081
      targetPort: 8081
  selector:
    io.kompose.service: microservice-2
status:
  loadBalancer: {}
