apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: microservice-2
  name: microservice-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: microservice-2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: microservice-2
    spec:
      containers:
        - image: microservice2
          name: microservice-2
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
