apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: microservice-1-tcp
  name: microservice-1-tcp
spec:
  ports:
    - name: "28080"
      port: 28080
      targetPort: 8080
  selector:
    io.kompose.service: microservice-1
  type: LoadBalancer
status:
  loadBalancer: {}
