apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: microservice-1
  name: microservice-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: microservice-1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: microservice-1
    spec:
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
          image: microservice
          name: microservice-1
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
